---

- name: remove conflicting packages
  ansible.builtin.package:
    state: absent
    name:
      # https://github.com/longhorn/longhorn/issues/3089
      - device-mapper-multipath

# https://longhorn.io/docs/1.1.2/deploy/install/#installation-requirements
- name: install longhorn dependencies
  ansible.builtin.package:
    state: present
    name:
      - iscsi-initiator-utils
      - nfs-utils
      - bash
      - curl
      - util-linux # findmnt, lsblk, blkid
      - grep
      - gawk

- name: install selinux dependencies
  ansible.builtin.dnf:
    update_cache: yes
    disable_gpg_check: yes # cause of the rpm
    name:
      - container-selinux
      - selinux-policy-base
      - https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/k3s-selinux-0.2-1.el7_8.noarch.rpm

- name: disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
