---

- name: install dependencies
  ansible.builtin.apt:
    state: present
    name:
      # https://longhorn.io/docs/1.1.2/deploy/install/#installation-requirements
      - open-iscsi
      - nfs-common
      - bash
      - curl
      - util-linux # findmnt, lsblk, blkid
      - grep
      - mawk

# longhorn (NFSv4) doesn't need it to listen
- name: stop and disable rpcbind
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - rpcbind.service
    - rpcbind.socket

- name: add k3s configuration
  ansible.builtin.template:
    src: "config.{{ k3s_role }}.yaml"
    dest: /etc/rancher/k3s/config.yaml
    mode: 0600
    owner: root
    group: root
  notify:
    - restart k3s

- name: add audit policy
  ansible.builtin.copy:
    src: audit.yaml
    dest: /var/lib/rancher/k3s/server/audit.yaml
    mode: 0600
    owner: root
    group: root
  notify:
    - restart k3s

- name: add PSA
  ansible.builtin.copy:
    src: psa.yaml
    dest: /var/lib/rancher/k3s/server/psa.yaml
    mode: 0600
    owner: root
    group: root
  notify:
    - restart k3s

# https://rancher.com/docs/k3s/latest/en/installation/private-registry/
- name: add private registries
  ansible.builtin.template:
    src: registries.yaml
    dest: /etc/rancher/k3s/registries.yaml
    mode: 0600
    owner: root
    group: root
  notify:
    - restart k3s

- name: add sysctl hardening
  ansible.builtin.copy:
    src: 90-kubelet.conf
    dest: /etc/sysctl.d/90-kubelet.conf
    mode: 0644
    owner: root
    group: root
  notify:
   - apply sysctl

- name: add helm charts
  ansible.builtin.get_url:
    url: "{{ item.src }}"
    dest: "/var/lib/rancher/k3s/server/static/charts/{{ item.dst }}"
    mode: 0600
    owner: root
    group: root
  changed_when: false
  when:
    - k3s_role == 'server'
  loop:
    - src: "https://github.com/cilium/charts/raw/master/cilium-{{ k3s_components.cilium }}.tgz"
      dst: "cilium-{{ k3s_components.cilium }}.tgz"
    - src: "https://charts.jetstack.io/charts/trust-manager-v{{ k3s_components.trust_manager }}.tgz"
      dst: "trust-manager-{{ k3s_components.trust_manager }}.tgz"
    - src: "https://charts.jetstack.io/charts/cert-manager-v{{ k3s_components.cert_manager }}.tgz"
      dst: "cert-manager-{{ k3s_components.cert_manager }}.tgz"
    - src: "https://traefik.github.io/charts/traefik/traefik-{{ k3s_components.traefik }}.tgz"
      dst: "traefik-{{ k3s_components.traefik }}.tgz"
    - src: "https://github.com/longhorn/charts/releases/download/longhorn-{{ k3s_components.longhorn }}/longhorn-{{ k3s_components.longhorn }}.tgz"
      dst: "longhorn-{{ k3s_components.longhorn }}.tgz"
    - src: "https://github.com/aquasecurity/helm-charts/releases/download/trivy-operator-{{ k3s_components.trivy_operator }}/trivy-operator-{{ k3s_components.trivy_operator }}.tgz"
      dst: "trivy-operator-{{ k3s_components.trivy_operator }}.tgz"
    - src: "https://kyverno.github.io/kyverno/kyverno-{{ k3s_components.kyverno }}.tgz"
      dst: "kyverno-{{ k3s_components.kyverno }}.tgz"

- name: add kustomizations
  ansible.builtin.copy:
    dest: "/var/lib/rancher/k3s/server/manifests/{{ item.dst }}"
    mode: 0600
    owner: root
    group: root
    content: |
      {{ item.src }}
  when:
    - k3s_role == 'server'
  loop:
    - src: "{{ lookup('kubernetes.core.kustomize', dir='https://github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=v' + k3s_components.external_snapshotter) }}"
      dst: external-snapshotter-crds.yaml

- name: add remote manifests
  ansible.builtin.get_url:
    url: "{{ item.src }}"
    dest: "/var/lib/rancher/k3s/server/manifests/{{ item.dst }}"
    mode: 0600
    owner: root
    group: root
  changed_when: false
  when:
    - k3s_role == 'server'
  loop:
    - src: "https://github.com/prometheus-operator/prometheus-operator/releases/download/v{{ k3s_components.prometheus_operator }}/stripped-down-crds.yaml"
      dst: "prometheus-operator-crds.yaml"

- name: add local manifests
  ansible.builtin.template:
    src: "manifests/{{ item }}"
    dest: "/var/lib/rancher/k3s/server/manifests/{{ item }}"
    mode: 0600
    owner: root
    group: root
  when:
    - k3s_role == 'server'
  loop:
    - cert-manager.yaml
    - cilium.yaml
    - ciliumclusterwidenetworkpolicy.yaml
    - external-dns.yaml
    - external-snapshotter.yaml
    - intel-gpu.yaml
    - kube-state-metrics.yaml
    - kube-system.yaml
    - kubernetes-api.yaml
    - kyverno.yaml
    - local-path-provisioner-override.yaml
    - longhorn.yaml
    - metrics-server/networkpolicy.yaml
    - metrics-server/servicemonitor.yaml
    - monitoring-system.yaml
    - monitoring.yaml
    - node-exporter.yaml
    - prometheus-agent.yaml
    - prometheus-operator.yaml
    - traefik-override.yaml
    - trivy-operator.yaml
    - vector-events.yaml
    - vector-logs.yaml
