---

- name: add audit policy
  ansible.builtin.copy:
    src: audit.yaml
    dest: /var/lib/rancher/k3s/server/audit.yaml
    mode: 0600
    owner: root
    group: root
  notify:
    - restart k3s

- name: adjust configuration
  ansible.builtin.template:
    src: "config.{{ k3s_role }}.yaml"
    dest: /etc/rancher/k3s/config.yaml
    mode: 0600
    owner: root
    group: root
  notify:
    - restart k3s

- name: add PSA
  ansible.builtin.copy:
    src: psa.yaml
    dest: /var/lib/rancher/k3s/server/psa.yaml
    mode: 0600
    owner: root
    group: root
  notify:
    - restart k3s

# DISCLAIMER: this is depdency to cillium configuration
- name: add prometheus-operator
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v{{ k3s_prometheus_operator_version }}/bundle.yaml"
    dest: /var/lib/rancher/k3s/server/manifests/prometheus-operator.yaml
    mode: 0600
    owner: root
    group: root
  changed_when: false
  when:
    - k3s_role == 'server'

- name: add cilium
  ansible.builtin.template:
    src: cilium.yaml
    dest: /var/lib/rancher/k3s/server/manifests/cilium.yaml
    mode: 0600
    owner: root
    group: root
  when:
    - k3s_role == 'server'
  notify:
    - restart k3s

- name: harden sysctl
  ansible.builtin.copy:
    src: 90-kubelet.conf
    dest: /etc/sysctl.d/90-kubelet.conf
    mode: 0644
    owner: root
    group: root

- name: apply hardened/hardened sysctl
  ansible.builtin.systemd:
    name: systemd-sysctl.service
    state: restarted
    daemon_reload: true
  changed_when: false
