---

- name: add audit policy
  ansible.builtin.copy:
    src: audit.yaml
    dest: /var/lib/rancher/k3s/server/audit.yaml
    mode: 0600
    owner: root
    group: root
  notify:
    - restart k3s

- name: adjust configuration
  ansible.builtin.template:
    src: "config.{{ k3s_role }}.yaml"
    dest: /etc/rancher/k3s/config.yaml
    mode: 0600
    owner: root
    group: root
  notify:
    - restart k3s

- name: add PSA
  ansible.builtin.copy:
    src: psa.yaml
    dest: /var/lib/rancher/k3s/server/psa.yaml
    mode: 0600
    owner: root
    group: root
  notify:
    - restart k3s

- name: add crds
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/var/lib/rancher/k3s/server/manifests/{{ item.name }}"
    mode: 0600
    owner: root
    group: root
  changed_when: false
  loop:
    - name: prometheus-operator.yaml
      url: "https://github.com/prometheus-operator/prometheus-operator/releases/download/v{{ k3s_prometheus_operator_version }}/stripped-down-crds.yaml"
    - name: gatewayclasses.yaml
      url: "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v{{ k3s_gateway_api_version }}/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml"
    - name: gateways.yaml
      url: "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v{{ k3s_gateway_api_version }}/config/crd/standard/gateway.networking.k8s.io_gateways.yaml"
    - name: httproutes.yaml
      url: "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v{{ k3s_gateway_api_version }}/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml"
    - name: referencegrants.yaml
      url: "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v{{ k3s_gateway_api_version }}/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml"
    - name: grpcroutes.yaml
      url: "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v{{ k3s_gateway_api_version }}/config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml"
    - name: tlsroutes.yaml
      url: "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v{{ k3s_gateway_api_version }}/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml"
  when:
    - k3s_role == 'server'

- name: add cilium chart
  ansible.builtin.get_url:
    url: "https://github.com/cilium/charts/raw/master/cilium-{{ k3s_cilium_version }}.tgz"
    dest: "/var/lib/rancher/k3s/server/static/charts/cilium-{{ k3s_cilium_version }}.tgz"
    mode: 0600
    owner: root
    group: root
  changed_when: false
  when:
    - k3s_role == 'server'

- name: add manifests
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/var/lib/rancher/k3s/server/manifests/{{ item }}"
    mode: 0600
    owner: root
    group: root
  when:
    - k3s_role == 'server'
  loop:
    - cilium.yaml
    - persistentvolumes.yaml
  notify:
    - restart k3s

- name: harden sysctl
  ansible.builtin.copy:
    src: 90-kubelet.conf
    dest: /etc/sysctl.d/90-kubelet.conf
    mode: 0644
    owner: root
    group: root

- name: apply hardened/hardened sysctl
  ansible.builtin.systemd:
    name: systemd-sysctl.service
    state: restarted
    daemon_reload: true
  changed_when: false

- name: patch k3s-uninstall.sh
  ansible.posix.patch:
    src: k3s-killall.patch
    dest: /usr/local/bin/k3s-killall.sh

- name: kubectl completion bash
  ansible.builtin.command: kubectl completion bash
  register: kubectl_completion
  changed_when: false
   
- name: add completion
  ansible.builtin.copy:
    content: "{{ kubectl_completion.stdout }}"
    dest: /etc/bash_completion.d/kubectl
    mode: 0644
    owner: root
    group: root
