---

- name: remove conflicting packages
  ansible.builtin.apt:
    state: absent
    name:
      # https://github.com/longhorn/longhorn/issues/3089
      - multipath-tools

- name: install dependencies
  ansible.builtin.apt:
    state: present
    name:
      # https://longhorn.io/docs/1.1.2/deploy/install/#installation-requirements 
      - open-iscsi
      - nfs-common
      - bash
      - curl
      - util-linux # findmnt, lsblk, blkid
      - grep
      - mawk
      # networkpolicy logging
      - ulogd2
      - ulogd2-json

# longhorn (NFSv4) doesn't need it to listen
- name: stop and disable rpcbind
  ansible.builtin.systemd:
    name: rpcbind.service
    state: stopped
    enabled: false

- name: stop and disable rpcbind.socket
  ansible.builtin.systemd:
    name: rpcbind.socket
    state: stopped
    enabled: false

- name: switch to legacy ip(6)tables
  community.general.alternatives:
    name: "{{ item }}"
    path: "/usr/sbin/{{ item }}-legacy"
  when:
    - ansible_distribution == 'Debian'
  loop:
    - iptables
    - ip6tables
  notify:
    - reboot
