---

- name: install dependencies
  ansible.builtin.apt:
    state: present
    name:
      # https://longhorn.io/docs/1.1.2/deploy/install/#installation-requirements 
      - open-iscsi
      - nfs-common
      - bash
      - curl
      - util-linux # findmnt, lsblk, blkid
      - grep
      - mawk
      # cillium (DISCLAIMER: bash is already present, used only as dummy value instead of empty string)
      - "{% if ansible_distribution == 'Ubuntu' and ansible_architecture != 'x86_64' %}linux-modules-extra-raspi{% else %}bash{% endif %}"

# longhorn (NFSv4) doesn't need it to listen
- name: stop and disable rpcbind
  ansible.builtin.systemd:
    name: rpcbind.service
    state: stopped
    enabled: false

- name: stop and disable rpcbind.socket
  ansible.builtin.systemd:
    name: rpcbind.socket
    state: stopped
    enabled: false
