---

- name: download k3s-install.sh
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: 0700
    owner: root
    group: root

# DISCLAIMER: for etcd cluster use this first: k3s server --cluster-init
- name: execute k3s-install.sh
  ansible.builtin.shell: /tmp/k3s-install.sh
  environment:
    INSTALL_K3S_EXEC: "{{ k3s_role }}"
    INSTALL_K3S_SKIP_START: "true"
    INSTALL_K3S_SKIP_ENABLE: "true"
    INSTALL_K3S_SKIP_SELINUX_RPM: "true"
    INSTALL_K3S_VERSION: "v{{ k3s.version }}"

- name: rm k3s-install.sh
  ansible.builtin.file:
    path: /tmp/k3s-install.sh
    state: absent
  notify:
    - reboot
