---

- name: mkdirs
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: 0700
    owner: root
    group: root
  loop:
    - /var/lib/rancher/k3s/server/logs
    - /var/lib/rancher/k3s/server/manifests
    - /var/lib/rancher/k3s/server/static/charts
    - /etc/rancher/k3s

- name: check k3s is installed
  ansible.builtin.command: k3s --version
  register: k3s_installed
  failed_when: false
  changed_when: false

- ansible.builtin.import_tasks: install.yml
  when: k3s_installed.rc != 0 or k3s_installed.stdout_lines[0].split(' ')[2].split('+')[0].replace('v', '') is version(k3s_version.split('+')[0], '<')

- ansible.builtin.import_tasks: dependencies.yml

- ansible.builtin.import_tasks: configuration.yml

# https://rancher.com/docs/k3s/latest/en/installation/private-registry/
- name: configure private registries
  ansible.builtin.template:
    src: registries.yaml
    dest: /etc/rancher/k3s/registries.yaml
    mode: 0600
    owner: root
    group: root
  notify:
    - restart k3s

- name: start k3s
  ansible.builtin.systemd:
    name: k3s{% if k3s_role == 'agent' %}-agent{% endif %}.service
    state: started
    enabled: true

# TODO: https://kubernetes.io/docs/concepts/architecture/garbage-collection/#image-maximum-age-gc
- name: add k3s image prune cronjob
  ansible.builtin.cron:
    user: root
    name: k3s image prune
    job: /usr/local/bin/k3s crictl rmi --prune
    special_time: weekly
