---

apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-deny-all-ingress

spec:
  description: Deny all ingress by default
  endpointSelector: {}
  ingress:
    - fromEndpoints: []

---

apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-allow-prometheus-agent

spec:
  description: Allow all ingress traffic from prometheus-agent
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring-system
            app.kubernetes.io/name: prometheus-agent

# ---

# apiVersion: cilium.io/v2
# kind: CiliumClusterwideNetworkPolicy
# metadata:
#   name: default-deny-egress-world

# spec:
#   description: Deny allow egress traffic to world (unless explicitly allowed)
#   endpointSelector: {}
#   egress:
#     - toEntities:
#         - world

---

apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-node-ingress

spec:
  nodeSelector:
    matchLabels: {}
  ingress:
    - fromEntities:
        - host
        - cluster
        - remote-node
    - fromCIDR: {{ k3s_firewall.whitelist }}
      toPorts:
        - ports:
            # ssh
            - port: "22"
              protocol: TCP
            # nfs
            - port: "2049"
              protocol: TCP
    - fromCIDR: {{ k3s_firewall.whitelist }}
      icmps: [{}]
