---

apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-deny-all-ingress

spec:
  description: Deny all ingress by default
  endpointSelector: {}
  ingress:
    - fromEntities:
        # DISCLAIMER: bypass for the webhookd on remote-node timeout
        - remote-node

---

apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-allow-prometheus-agent

spec:
  description: Allow all ingress traffic from prometheus-agent
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring-system
            app.kubernetes.io/name: prometheus-agent

# ---

# apiVersion: cilium.io/v2
# kind: CiliumClusterwideNetworkPolicy
# metadata:
#   name: default-deny-egress-world

# spec:
#   description: Deny allow egress traffic to world (unless explicitly allowed)
#   endpointSelector: {}
#   egress:
#     - toEntities:
#         - world

---

apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-allow-dns # allow ~ intercept

spec:
  endpointSelector:
    matchExpressions:
      - key: io.kubernetes.pod.namespace
        operator: NotIn
        values:
          - kube-system
  enableDefaultDeny:
    egress: false
    ingress: false
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: TCP
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"

---

apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-node-ingress

spec:
  nodeSelector:
    matchLabels: {}
  ingress:
    - fromEntities:
        - host
        - cluster
        - remote-node
        - kube-apiserver
    - fromCIDR: {{ k3s_firewall.whitelist }}
      toPorts:
        - ports:
            # ssh
            - port: "22"
              protocol: TCP
            # nfs
            - port: "2049"
              protocol: TCP
    - fromCIDR: {{ k3s_firewall.whitelist }}
      icmps: [{}]
