{% raw %}
---

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-workload-defaults

spec:
  rules:
    - name: add-revisionhistorylimit
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
      mutate:
        patchStrategicMerge:
          spec:
            revisionHistoryLimit: 3

    - name: add-ca-certificates
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                # prevent cyclic dependency
                - cert-manager
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
      mutate:
        foreach:
          - list: request.object.spec.containers
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    volumeMounts:
                      - name: ca
                        mountPath: /etc/ssl/certs
                        readOnly: true
                volumes:
                  - name: ca
                    configMap:
                      name: trusted-ca-bundle

    # - name: mutate-emptydir
    #   match:
    #     any:
    #     - resources:
    #         kinds:
    #         - Pod
    #   mutate:
    #     foreach:
    #     - list: "request.object.spec.volumes[]"
    #       preconditions:
    #         all:
    #         - key: "{{element.keys(@)}}"
    #           operator: AnyIn
    #           value: emptyDir
    #         - key: "{{element.emptyDir.sizeLimit || ''}}"
    #           operator: Equals
    #           value: ''
    #       patchesJson6902: |-
    #         - path: "/spec/volumes/{{elementIndex}}/emptyDir/sizeLimit"
    #           op: add
    #           value: 100Mi

    - name: add-requests
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        any:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
      mutate:
        foreach:
          - list: request.object.spec.containers[]
            patchStrategicMerge:
              spec:
                enableServiceLinks: false
                containers:
                  - (name): "{{ element.name }}"
                    resources:
                      requests:
                        +(memory): 128Mi
                        +(cpu): 100m
                    env:
                      - name: TZ
                        value: Europe/Prague

---

apiVersion: kyverno.io/v2
kind: ClusterCleanupPolicy
metadata:
  name: delete-old-pods

spec:
  match:
    any:
      - resources:
          kinds:
            - Pod
  conditions:
    all:
      - key: "{{ time_diff('{{target.metadata.creationTimestamp}}','{{ time_now_utc() }}') }}"
        operator: GreaterThan
        value: "168h0m0s"
  schedule: "0 */8  * * *"

{% endraw %}
