---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system

spec:
  chart: https://{{ k3s_host }}:6443/static/charts/cilium-{{ k3s_cilium_version }}.tgz
  targetNamespace: kube-system
  bootstrap: true
  valuesContent: |-
    kubeProxyReplacement: true
    # DISCLAIMER: this will bite me in the ass in setup with multiple masters without LB
    k8sServiceHost: {{ k3s_host }}
    k8sServicePort: 6443
    routingMode: tunnel
    tunnelProtocol: geneve
    loadbalancer:
      mode: dsr
      dsrDispatch: geneve
    gatewayAPI:
      enabled: true
    encryption:
      enabled: true
      type: wireguard
      nodeEncryption: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    operator:
      replicas: 1
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    hubble:
      enabled: true
      export:
        static:
          enabled: true
          filePath: /var/run/cilium/hubble/events.log
          allowList:
            - '{"verdict":["VERDICT_UNKNOWN","DROPPED","ERROR","AUDIT"]}'
            # VERDICT_UNKNOWN = 0;
            # FORWARDED = 1;
            # DROPPED = 2;
            # ERROR = 3;
            # AUDIT = 4;
            # REDIRECTED = 5;
      metrics:
        enabled: 
          - dns 
          - drop
          - flow
          - flows-to-world
          - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
          - icmp
          - port-distribution
          - tcp
        enableOpenMetrics: true
        serviceMonitor:
          enabled: true
      relay:
        enabled: true
        prometheus:
          enabled: true
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
        frontend:
          server:
            ipv6:
              enabled: false
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: [ 10.42.0.0/16 ]
    l2announcements:
      enabled: true
