---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coredns
  namespace: kube-system

spec:
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system

data:
  log.override: |
    log

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coredns
  namespace: kube-system

spec:
  selector:
    matchLabels:
      kubernetes.io/name: CoreDNS
  endpoints:
    - port: metrics

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet
  namespace: kube-system

spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
  endpoints:
    - port: https-metrics
      honorLabels: true
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - sourceLabels: [ __metrics_path__ ]
          targetLabel: metrics_path
    - port: https-metrics
      path: /metrics/cadvisor
      honorLabels: true
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
        serverName: kubernetes
      relabelings:
        - sourceLabels: [ __metrics_path__ ]
          targetLabel: metrics_path
    - port: https-metrics
      path: /metrics/probes
      honorLabels: true
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - sourceLabels: [ __metrics_path__ ]
          targetLabel: metrics_path

# DISCLAIMER: k3s has all kubenernetes metrics on all endpoints, it makes sense, to scrape them only once, from kubelet (https://github.com/k3s-io/k3s/issues/3619)

---

# DISCLAIMER: wilcard certificate and dns record are used so that all domain names do not leak to public

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt
  namespace: kube-system

spec:
  commonName: "{{ k3s_tls.external.domain }}"
  dnsNames:
    - "{{ k3s_tls.external.domain }}"
    - "*.{{ k3s_tls.external.domain }}"
  secretName: letsencrypt-certificate
  issuerRef:
    name: letsencrypt-ca
    kind: ClusterIssuer
{% raw %}
---

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-letsencrypt-certificate

spec:
  rules:
    - name: add-secret
      match:
        any:
          - resources:
              kinds:
                - Namespace
      generate:
        generateExisting: true
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: letsencrypt-certificate
        namespace: "{{ request.object.metadata.name }}"
        clone:
          name: letsencrypt-certificate
          namespace: kube-system

{% endraw %}
