---

apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: kubernetes-whitelist
  namespace: default

spec:
  ipAllowList:
    sourceRange: {{ k3s_api.whitelist }}

---

apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kubernetes
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/target: "{{ k3s_loadbalancer.pools[0].start }}"

spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`{{ k3s_api.host }}`)
      services:
        - name: kubernetes
          port: 443
      middlewares:
        - name: kubernetes-whitelist

  tls:
    passthrough: true
