---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coredns
  namespace: kube-system

spec:
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
        - port: 9153
          protocol: TCP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system

data:
  log.override: |
    log

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coredns
  namespace: kube-system

spec:
  selector:
    matchLabels:
      kubernetes.io/name: CoreDNS
  endpoints:
    - port: metrics

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet
  namespace: kube-system

spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
  endpoints:
    - port: https-metrics
      honorLabels: true
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - sourceLabels: [ __metrics_path__ ]
          targetLabel: metrics_path
    - port: https-metrics
      path: /metrics/cadvisor
      honorLabels: true
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
        serverName: kubernetes
      relabelings:
        - sourceLabels: [ __metrics_path__ ]
          targetLabel: metrics_path
    - port: https-metrics
      path: /metrics/probes
      honorLabels: true
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - sourceLabels: [ __metrics_path__ ]
          targetLabel: metrics_path
    - port: http-metrics
      path: /metrics/slis
      honorLabels: true
      interval: 5s

# DISCLAIMER: k3s has all kubenernetes metrics on all endpoints, it makes sense, to scrape them only once, from kubelet (https://github.com/k3s-io/k3s/issues/3619)
