---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kyverno
  namespace: kube-system

spec:
  chart: https://%{KUBERNETES_API}%/static/charts/kyverno-{{ k3s_components.kyverno }}.tgz
  targetNamespace: policy-system
  createNamespace: true
  # https://github.com/kyverno/kyverno/blob/main/charts/kyverno/values.yaml
  valuesContent: |-
    fullnameOverride: kyverno
    grafana:
      enabled: true
      configMapName: kyverno-dashboard
      namespace: monitoring
      labels:
        grafana_dashboard: "true"
    # global:
    #   caCertificates:
    #     volume:
    #       configMap:
    #         name: trusted-ca-bundle
    admissionController:
      networkPolicy:
        enabled: true
      serviceMonitor:
        enabled: true
    backgroundController:
      networkPolicy:
        enabled: true
      serviceMonitor:
        enabled: true
    cleanupController:
      networkPolicy:
        enabled: true
      serviceMonitor:
        enabled: true
    reportsController:
      networkPolicy:
        enabled: true
      serviceMonitor:
        enabled: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:background-controller:rbac
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno

rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:admission-controller:rbac
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno

rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:background-controller:secrets
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno

rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:admission-controller:secrets
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno

rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:cleanup-controller:pods
  labels:
    app.kubernetes.io/component: cleanup-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno

rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
      - delete
