---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: trivy-operator
  namespace: kube-system

spec:
  chart: https://%{KUBERNETES_API}%/static/charts/trivy-operator-{{ k3s_components.trivy_operator }}.tgz
  targetNamespace: trivy-system
  createNamespace: true
  # https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml
  valuesContent: |-
    operator:
      metricsFindingsEnabled: true
      metricsVulnIdEnabled: true
      metricsExposedSecretInfo: true
      metricsConfigAuditInfo: true
      metricsRbacAssessmentInfo: true
      metricsInfraAssessmentInfo: true
      metricsImageInfo: true
      metricsClusterComplianceInfo: true
      scanJobsConcurrentLimit: 1
    trivy:
      command: rootfs
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
    trivyOperator:
      skipResourceByLabels: trivy.io/skip
      scanJobPodTemplateContainerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsUser: 0
    serviceMonitor:
      enabled: true
    resources:
      requests:
        cpu: 40m
        memory: 512Mi

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: trivy-operator
  namespace: trivy-system

spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: trivy-operator
  policyTypes:
    - Egress
    - Ingress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: vector-events
      ports:
        - protocol: TCP
          port: 80
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 6443
