---

- name: restart k3s
  ansible.builtin.systemd:
    name: k3s{% if k3s_role == 'agent' %}-agent{% endif %}.service
    state: restarted
    daemon_reload: true

- name: restart ulogd2
  ansible.builtin.systemd:
    name: ulogd2.service
    state: restarted
    daemon_reload: true

- name: reboot
  ansible.builtin.reboot:
    reboot_timeout: 120
  when: not (skip_handlers | default('no'))
