---

- name: restart k3s
  ansible.builtin.systemd:
    name: k3s.service
    state: restarted
    daemon_reload: yes

- name: restart k3s-agent
  ansible.builtin.systemd:
    name: k3s-agent.service
    state: restarted
    daemon_reload: yes

- name: reboot
  ansible.builtin.reboot:
    reboot_timeout: 120
  when: not (skip_handlers | default('no'))

