---

apiVersion: audit.k8s.io/v1
kind: Policy

omitStages:
  - RequestReceived
rules:
  # Ignore reading stuff
  - level: None
    verbs: ["get", "watch", "list"]
  
  - level: None
    userGroups:
    # Do not log from kube-system accounts
    - system:serviceaccounts:kube-system
    # Don't log nodes communications
    - system:nodes
  
  - level: None
    users:
    - system:apiserver
    - system:kube-scheduler
    - system:kube-controller-manager
    - system:node
    - system:k3s-supervisor

  # Log metadata about writing stuff
  - level: Metadata
